accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views  # Apéndice


urlpatterns = [
    path('signup/', views.UserCreateAndLoginView.as_view(), name='signup'),    # cambiar
    path('login/', LoginView.as_view(
        redirect_authenticated_user=True,
        template_name='accounts/login.html'
    ), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_detail/<int:pk>/', views.UserDetail.as_view(), name='user_detail'),
    path('user_update/<int:pk>/', views.UserUpdate.as_view(), name='user_update'),
    path('password_change/', views.PasswordChange.as_view(), name='password_change'),
    path('password_change/done/', views.PasswordChangeDone.as_view(), name='password_change_done'),
    path('user_delete/<int:pk>/', views.UserDelete.as_view(), name='user_delete'),
]

blog/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('create', views.create, name='create'),
    path('detail/<int:article_id>', views.detail, name='detail'),
    path('edit/<int:article_id>', views.edit, name='edit'),
    path('delete/<int:article_id>', views.delete, name='delete'),
]

loginApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LogoutView
from django.urls import reverse_lazy
urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('logout/', LogoutView.as_view(next_page=reverse_lazy('login')), name='logout'),
]

accounts/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin, UserManager
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class CustomUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(
        _('username'),
        max_length=150,
    )
    email = models.EmailField(
        _('email address'),
        unique=True,
    )
    age = models.PositiveIntegerField(('Age'), default=0, blank=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(_('staff status'), default=False)
    is_active = models.BooleanField(_('active'), default=True)
    data_joined = models.DateTimeField(_('data joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')
        db_table = 'users'
        swappable = 'AUTH_USER_MODEL'

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        send_mail(subject, message, from_email, [self.email], **kwargs)

blog/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()

    def __str__(self):
        return f'{self.title}, {self.content}'

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import CustomUser
from django import forms


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('email', 'age')
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = (
            'username',
            'email',
            'age',
        )

blog/forms.py
from django import forms


class ArticleForm(forms.Form):
    title = forms.CharField(label='Title', max_length=255)
    content = forms.CharField(label='Content', widget=forms.Textarea())

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView
from django.contrib.auth import login, authenticate
from .forms import (
    CustomUserCreationForm,
    UserUpdateForm,
)
from django.contrib.auth import get_user_model
from django.views.generic import (
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse
from django.contrib.auth.views import (
    PasswordChangeView, PasswordChangeDoneView
)
from django.contrib.auth.mixins import UserPassesTestMixin 
User = get_user_model()

class UserCreateAndLoginView(CreateView):
    form_class = CustomUserCreationForm
    template_name = "accounts/signup.html"
    success_url = reverse_lazy("blog:index")

    def form_valid(self, form):
        response = super().form_valid(form)
        email = form.cleaned_data.get("email")
        raw_pw = form.cleaned_data.get("password1")
        user = authenticate(email=email, password=raw_pw)
        login(self.request, user)
        return response

class OnlyYouMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.pk == self.kwargs['pk'] or user.is_superuser

class UserDetail(OnlyYouMixin, DetailView):
    model = User
    template_name = 'accounts/user_detail.html'

class UserUpdate(OnlyYouMixin, UpdateView):
    model = User
    form_class = UserUpdateForm
    template_name = 'accounts/user_edit.html'

    def get_success_url(self):
        return reverse('user_detail', kwargs={'pk': self.kwargs['pk']})
class PasswordChange(PasswordChangeView):
    template_name = 'accounts/password_change.html'


class PasswordChangeDone(PasswordChangeDoneView):
    template_name = 'accounts/user_detail.html'
    
class UserDelete(OnlyYouMixin, DeleteView):
    model = User
    template_name = 'accounts/user_delete.html'
    success_url = reverse_lazy('login')

blog/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from .models import Article
from .forms import ArticleForm


def index(request):
    articles = Article.objects.all()
    params = {
        'articles': articles,
    }
    return render(request, 'blog/index.html', params)


def create(request):
    if (request.method == 'POST'):
        title = request.POST['title']
        content = request.POST['content']
        article = Article(title=title, content=content)
        article.save()
        return redirect('blog:index')
    else:
        params = {
            'form': ArticleForm(),
        }
        return render(request, 'blog/create.html', params)


def detail(request, article_id):
    article = Article.objects.get(id=article_id)
    params = {
        'article': article,
    }
    return render(request, 'blog/detail.html', params)


def edit(request, article_id):
    article = Article.objects.get(id=article_id)
    if (request.method == 'POST'):
        article.title = request.POST['title']
        article.content = request.POST['content']
        article.save()
        return redirect('blog:detail', article_id)
    else:
        form = ArticleForm(initial={
            'title': article.title,
            'content': article.content,
        })
        params = {
            'article': article,
            'form': form,
        }
        return render(request, 'blog/edit.html', params)


def delete(request, article_id):
    article = Article.objects.get(id=article_id)
    if (request.method == 'POST'):
        article.delete()
        return redirect('blog:index')
    else:
        params = {
            'article': article,
        }
        return render(request, 'blog/delete.html', params)

accounts/templates/accounts/login.html
{% extends "base.html" %}

{% block main %}
<h1>Página de inicio de sesión</h1>

<form method="post">
  {% csrf_token %}
  <input type="hidden" name="next" value="{{ next }}" />
  {{ form.as_p }}
  <input type="submit" value="Iniciar sesión">
</form>
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "base.html" %}

{% block main %}
<h2>Cambiar contraseña</h2>
<form action="" method="POST">
  {{ form.as_p }}
  {% csrf_token %}
  <button type="submit">Cambiar</button>
</form>
<a href="{% url 'user_detail' user.id %}">Regresar</a>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base.html" %}

{% block main %}
<h2>Página de registro de usuario</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Inscripción">
</form>
{% endblock %}

accounts/templates/accounts/user_delete.html
{% extends "base.html" %}

{% block main %}
<h2>Página de eliminación de usuario</h2>
<table>
  <tbody>
    <tr>
      <th>Nombre de usuario</th>
      <td>{{ user.username }}</td>
    </tr>
    <tr>
      <th>Dirección de correo electrónico</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>Age</th>
      <td>{{ user.age }}</td>
    </tr>
  </tbody>
</table>

<form action="{% url 'user_delete' user.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Dar de baja">
</form>

<a href="{% url 'user_detail' user.id %}">Regresar</a>
{% endblock %}

accounts/templates/accounts/user_detail.html
{% extends "base.html" %}

{% block main %}
<h2>Página de detalles del usuario</h2>
<table class="table">
  <tbody>
    <tr>
      <th>Nombre de usuario</th>
      <td>{{ user.username }}</td>
    </tr>
    <tr>
      <th>Dirección de correo electrónico</th>
      <td>{{ user.email }}</td>
    </tr>
    <tr>
      <th>Age</th>
      <td>{{ user.age }}</td>
    </tr>
  </tbody>
</table>
<a href="{% url 'user_update' user.pk %}">Editar</a>
<a href="{% url 'password_change' %}">Cambiar contraseña</a>    <!-- Apéndice -->
{% endblock %}

accounts/templates/accounts/user_edit.html
{% extends "base.html" %}

{% block main %}
<h2>Página de edición de la información de usuario</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Actualizar.">
</form>
<a href="{% url 'user_detail' user.id %}">Regresar</a>
<a href="{% url 'user_delete' user.id %}">Dar de baja</a>
{% endblock %}

blog/templates/blog/create.html
{% extends "base.html" %}

{% block main %}
<h1>New Blog</h1>
<form action="{% url 'blog:create' %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Create Blog">
</form>

<br>

<a href="{% url 'blog:index' %}">Back</a>
{% endblock %}

blog/templates/blog/delete.html
{% extends "base.html" %}

{% block main %}
<p>
  <strong>Title:</strong>
  {{article.title}}
</p>

<p>
  <strong>Content:</strong>
  {{article.content}}
</p>
<form action="{% url 'blog:delete' article.id %}" method="post">
  {% csrf_token %}
  <input type="submit" value="Delete">
</form>

<br>

<a href="{% url 'blog:index' %}">Back</a>
{% endblock %}

blog/templates/blog/detail.html
{% extends "base.html" %}

{% block main %}
<p>
  <strong>Title:</strong>
  {{article.title}}
</p>

<p>
  <strong>Content:</strong>
  {{article.content}}
</p>
<a href="{% url 'blog:index' %}">Back</a> |
<a href="{% url 'blog:edit' article.id %}">Edit</a>
{% endblock %}

blog/templates/blog/edit.html
{% extends "base.html" %}

{% block main %}
<h1>Editing Blog</h1>
<form action="{% url 'blog:edit' article.id %}" method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value="Update">
</form>

<br>

<a href="{% url 'blog:detail' article.id %}">Detail</a> |
<a href="{% url 'blog:index' %}">Back</a>

{% endblock %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block main %}
<h1>Blogs</h1>
<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th colspan="3"></th>
  </tr>
  {% for article in articles %}
  <tr>
    <td>{{article.title}}</td>
    <td>{{article.content}}</td>
    <td><a href="{% url 'blog:detail' article.id %}">Detail</a></td>
    <td><a href="{% url 'blog:edit' article.id %}">Edit</a></td>
    <td><a href="{% url 'blog:delete' article.id %}">Delete</a></td>
  </tr>
  {% endfor %}
</table>

<br>

<a href="{% url 'blog:create' %}">New Blog</a>

{% endblock %}

templates/base.html
{% load static %}

<html>

  <head>
    <meta charset="utf-8">
    <title>Blog</title>
    <link rel="stylesheet" href="{% static 'blog/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
  </head>

  <body>
    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li><a href="{% url 'blog:index' %}">Lista de blogs</a></li>
        <li><a href="{% url 'logout' %}">Cerrar sesión</a></li>
        <li><a href="{% url 'user_detail' user.pk %}">Información para los miembros</a></li>
        {% else %}
        <li><a href="{% url 'login' %}">Iniciar sesión</a></li>
        <li><a href="{% url 'signup' %}">Registrar usuario</a></li>
        {% endif %}
      </ul>
    </nav>
    <main>
      <div>
        {% block main %}
        {% endblock %}
      </div>
    </main>
  </body>

</html>